# Generated by Django 4.2.4 on 2023-08-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
